# -*- coding: utf-8 -*-
"""Sqlite codigo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGrTdv96C3SRWmE42VUIJ3mcyavuCE47
"""

#importaçoes

#importa o sqlite(banco de dados)
import sqlite3

#criar banco de dados
conn = sqlite3.connect('estoque.db', check_same_thread=False)
cursor = conn.cursor()

#tabela de usuarios
cursor.execute('''
create table if not exists usuarios (
    id integer primary key autoincrement,
    nome TEXT,
    email TEXT,
    senha TEXT
)
''')

#tabela de produtos
cursor.execute('''
create table if not exists produtos (
    id integer primary key autoincrement,
    nome TEXT,
    quantidade INTEGER,
    usuario_id INTEGER
)
''')

#salva as tabelas no banco de dados
conn.commit()



# Commented out IPython magic to ensure Python compatibility.
# %%writefile Cadastro_produtos.py
# 
# import sqlite3
# 
# def conectar_banco():
#     return sqlite3.connect("estoque.db")
# 
# def criar_tabela():
#     conexao = conectar_banco()
#     cursor = conexao.cursor()
#     cursor.execute('''
#     CREATE TABLE IF NOT EXISTS estoque (
#         codigo TEXT PRIMARY KEY,
#         nome_item TEXT,
#         quantidade REAL,
#         unidade_medida TEXT,
#         preco_unitario REAL,
#         preco_total REAL
#     )
#     ''')
#     conexao.commit()
#     conexao.close()
# 
# def cadastrar_produto():
#     print("\n--- CADASTRO DE PRODUTO ---")
# 
#     codigo = input("Digite o código do produto (001 a 999): ")
# 
#     if not codigo.isdigit() or len(codigo) != 3:
#         print("Erro: o código deve conter 3 números. Exemplo: 001.")
#         return
# 
#     nome_item = input("Digite o nome do item: ")
#     quantidade = float(input("Digite a quantidade em estoque: "))
#     unidade_medida = input("Digite a unidade de medida (un, kg, L, m): ")
#     preco_unitario = float(input("Digite o preço unitário: "))
# 
#     preco_total = quantidade * preco_unitario
# 
#     produto = {
#         "codigo": codigo,
#         "nome_item": nome_item,
#         "quantidade": quantidade,
#         "unidade_medida": unidade_medida,
#         "preco_unitario": preco_unitario,
#         "preco_total": preco_total
#     }
# 
#     conexao = conectar_banco()
#     cursor = conexao.cursor()
# 
#     try:
#         cursor.execute("""
#         INSERT INTO estoque (
#             codigo,
#             nome_item,
#             quantidade,
#             unidade_medida,
#             preco_unitario,
#             preco_total
#         )
#         VALUES (?, ?, ?, ?, ?, ?)
#         """, (
#             produto["codigo"],
#             produto["nome_item"],
#             produto["quantidade"],
#             produto["unidade_medida"],
#             produto["preco_unitario"],
#             produto["preco_total"]
#         ))
# 
#         conexao.commit()
#         print("\nProduto cadastrado com sucesso!")
#         print(f"Preço total em estoque: R$ {preco_total:.2f}")
# 
#     except sqlite3.IntegrityError:
#         print("\nErro: já existe um produto com esse código.")
# 
#     conexao.close()
# 
# 
# def listar_produtos():
#     conexao = conectar_banco()
#     cursor = conexao.cursor()
# 
#     cursor.execute("SELECT * FROM estoque")
#     produtos = cursor.fetchall()
# 
#     print("\n--- PRODUTOS CADASTRADOS ---")
# 
#     if len(produtos) == 0:
#         print("Nenhum produto cadastrado.")
#     else:
#         for produto in produtos:
#             print(f"""
# Código: {produto[0]}
# Nome: {produto[1]}
# Quantidade: {produto[2]}
# Unidade: {produto[3]}
# Preço unitário: R$ {produto[4]:.2f}
# Preço total: R$ {produto[5]:.2f}
# ------------------------------
# """)
# 
#     conexao.close()
# 
# 
# def menu():
#     criar_tabela()
# 
#     while True:
#         print("""
# ===== SISTEMA DE ESTOQUE =====
# 1 - Cadastrar produto
# 2 - Listar produtos
# 3 - Sair
# """)
# 
#         opcao = input("Escolha uma opção: ")
# 
#         if opcao == "1":
#             cadastrar_produto()
#         elif opcao == "2":
#             listar_produtos()
#         elif opcao == "3":
#             print("Sistema encerrado.")
#             break
#         else:
#             print("Opção inválida. Tente novamente.")
# 
# 
# menu()

!python Cadastro_produtos.py